CREATE TABLE devices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_number   VARCHAR(32),
    name            VARCHAR(255),
    ip_address      VARCHAR(255),
    location        TEXT NOT NULL,
    latitude        FLOAT,
    longitude       FLOAT,
    CONSTRAINT pk_devices PRIMARY KEY (id)
);

CREATE TABLE weather_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    device_id       BIGINT NULL,
    time            TIMESTAMP WITHOUT TIME ZONE,
    receive_time    TIMESTAMP WITHOUT TIME ZONE,
    temp            DOUBLE PRECISION,
    pressure        DOUBLE PRECISION,
    altitude        DOUBLE PRECISION,
    CONSTRAINT pk_weather_log PRIMARY KEY (id)
);

ALTER TABLE "weather_log" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON DELETE SET NULL ON UPDATE NO ACTION;
