version: "3.4"

services:
  meteorolog_db:
    image: meteorolog_db:latest
    restart: always
    environment:
      POSTGRES_DB: meteorolog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: meteorolog
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./_data_base:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: meteorolog_db
    hostname: meteorolog_db

  meteorolog_adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - meteorolog_db
    ports:
      - "8077:8080"
    container_name: meteorolog_adminer
    hostname: meteorolog_adminer

  meteorolog_frontend:
    image: meteorolog_frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - meteorolog_backend
    container_name: meteorolog_frontend
    hostname: meteorolog_frontend

  meteorolog_backend:
    image: meteorolog_backend:latest           
    ports:
      - "8090:8090"
    depends_on:
      - meteorolog_db
    volumes:
      - ./meteorolog.properties:/work/application.properties
    container_name: meteorolog_backend
    hostname: meteorolog_backend

